version: 0.0
os: linux
files:
  - source: phpinfo.php
    destination: /var/www/topgolf
permissions:
   - object: /opt/codedeploy-agent/deployment-root
     overwrite: true
     pattern: "**"
     owner: root
     group: root
     mode: 755
     type:
       - directory
   - object: /var/www/topgolf
     overwrite: true
     pattern: "**"
     owner: root
     group: root
     mode: 755
     type:
       - directory
